### ISSUE TITLE
Parameter '.combine' does not give consistent results

### ISSUE THREAD

**Issue by privefl** [RevolutionAnalytics/foreach#36]
I was expecting all of these to return a matrix, but the first one outputs a simple vector.

```r
library(foreach)

foreach(i = 1, .combine = "cbind") %do% {
  i + 1:10
}

foreach(i = 1:2, .combine = "cbind") %do% {
  i + 1:10
}

do.call("cbind", foreach(i = 1) %do% {
  i + 1:10
})
```

**Comment by bwlewis** [comment]
I agree that is not expected, but the do.call is not the right
analogy. More like Reduce (since .combine is a reduction function):

Reduce(cbind, 1:10)

which, counter-intuitively, returns a row vector. Also confusing.

Despite this weirdness, you can hack a fix into your example with an
explicit NULL init value:

foreach(i = 1, .combine = "cbind", .init=NULL) %do% { i + 1:10}

I agree that your original example should default to behaving like
this though. That would be intuitive.

**Comment by bwlewis** [comment]
Sorry my Reduce example was not thought through carefully. The correct
analogy is:

Reduce(cbind, list(1:10))

which produces the exact output of foreach. So sorry, it appears
foreach is doing the right thing here. Compare with:

Reduce(cbind, list(1:10, NULL))

Ignore my previous response!

**Comment by privefl** [comment]
So, the recommended solution would be to use 
`foreach(i = 1, .combine = "cbind", .init=NULL) %do% { i + 1:10}`
?

**Comment by bwlewis** [comment]
yes, that's what i recommend:  .combine should be thought of as Reduce.
This nice compact example would make a good addition to documentation
 somewhere.

**Comment by privefl** [comment]
Thanks
